//This file is automatically generated by [conv_audio.py]. Do not edit manually.
#ifndef audioAssetEnumh
#define audioAssetEnumh

enum AudioAssetName{
	_musThemeA, _musThemeA_Battle, _musThemeA_Peace, _musThemeB, _musThemeB_Battle, _musThemeC, _musThemeC_Battle, _musThemeC_Peace, _musThemeD, _musThemeD_Battle, _musThemeD_Peace, 
};

#endif