//This file is automatically generated by [conv_audio.py]. Do not edit manually.
#ifndef audioAssetEnumh
#define audioAssetEnumh

enum AudioAssetName{
	_musMainMenu, _musOpening, _musThemeA_Battle, _musThemeA_Peace, _musThemeB, _musThemeB_Battle, _musThemeC_Battle, _musThemeC_Peace, _musThemeD_Battle, _musThemeD_Peace, _musTitle, 
};

#endif