//This file is automatically generated by [assets_converter.py]. Do not edit manually.
#ifndef audioAssetEnumh
#define audioAssetEnumh

enum AudioAssetName{
	_SongTemplate, _ThemeA, _ThemeB, _ThemeC, 
};

#endif