//This file is automatically generated by [assets_converter.py]. Do not edit manually.
#include "audio_engine_internal.h"

extern cu8 _edmkick_data[];
AudioSample _edmkick = {
	.sampleStart = _edmkick_data, .sampleLength = 5907, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 45306,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _edmsnare_data[];
AudioSample _edmsnare = {
	.sampleStart = _edmsnare_data, .sampleLength = 8832, .loopEnd = 8832, .loopStart = 5888, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 60, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _hihat_data[];
AudioSample _hihat = {
	.sampleStart = _hihat_data, .sampleLength = 13614, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 36, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _fm_bass_data[];
AudioSample _fm_bass = {
	.sampleStart = _fm_bass_data, .sampleLength = 7511, .loopEnd = 7511, .loopStart = 5299, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 58, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _rave_lead_data[];
AudioSample _rave_lead = {
	.sampleStart = _rave_lead_data, .sampleLength = 25076, .loopEnd = 25076, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 57, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _50square_data[];
AudioSample _50square = {
	.sampleStart = _50square_data, .sampleLength = 2696, .loopEnd = 2696, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 352800,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 30, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _FM_Bell1_data[];
AudioSample _FM_Bell1 = {
	.sampleStart = _FM_Bell1_data, .sampleLength = 3968, .loopEnd = 3968, .loopStart = 3799, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 26, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _FM_Bass2_data[];
AudioSample _FM_Bass2 = {
	.sampleStart = _FM_Bass2_data, .sampleLength = 4378, .loopEnd = 4378, .loopStart = 3706, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 48, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

AudioSample *sampleList[] = {
	&_edmkick, &_edmsnare, &_hihat, &_fm_bass, &_rave_lead, &_50square, &_FM_Bell1, &_FM_Bass2
};

cu16 numSamples = 8;

extern AssetData _ThemeAAsset;
AssetData *assetsList[] = {
	&_ThemeAAsset
};

cu16 numAssets = 1;

