//This file is automatically generated by [song_converter.py]. Do not edit manually.
#include "audio_engine_internal.h"

extern cu8 _ChoirOohs_data[];
AudioSample _ChoirOohs = {
	.sampleStart = _ChoirOohs_data, .sampleLength = 13182, .loopEnd = 13182, .loopStart = 3789, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 33659,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _MaxVKick04_data[];
AudioSample _MaxVKick04 = {
	.sampleStart = _MaxVKick04_data, .sampleLength = 9918, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 36, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _MaxVSNARE1_data[];
AudioSample _MaxVSNARE1 = {
	.sampleStart = _MaxVSNARE1_data, .sampleLength = 4983, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _PianoHigh_data[];
AudioSample _PianoHigh = {
	.sampleStart = _PianoHigh_data, .sampleLength = 9533, .loopEnd = 9533, .loopStart = 8146, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 23417,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _kik_data[];
AudioSample _kik = {
	.sampleStart = _kik_data, .sampleLength = 16126, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 22326,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 176, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _snare_data[];
AudioSample _snare = {
	.sampleStart = _snare_data, .sampleLength = 12793, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 22326,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 155, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _Celesta2_data[];
AudioSample _Celesta2 = {
	.sampleStart = _Celesta2_data, .sampleLength = 1734, .loopEnd = 1734, .loopStart = 1590, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 50213,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _GuitarNylon_data[];
AudioSample _GuitarNylon = {
	.sampleStart = _GuitarNylon_data, .sampleLength = 9820, .loopEnd = 9820, .loopStart = 9576, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 31885,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _ModernTalkingchiptune_data[];
AudioSample _ModernTalkingchiptune = {
	.sampleStart = _ModernTalkingchiptune_data, .sampleLength = 2987, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 11163,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _ByEm022000_data[];
AudioSample _ByEm022000 = {
	.sampleStart = _ByEm022000_data, .sampleLength = 3997, .loopEnd = 3997, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 16043,
	.sampleType = 4, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 26, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _Hellotoallwho_data[];
AudioSample _Hellotoallwho = {
	.sampleStart = _Hellotoallwho_data, .sampleLength = 316, .loopEnd = 316, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 8163,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _knowsme_data[];
AudioSample _knowsme = {
	.sampleStart = _knowsme_data, .sampleLength = 158, .loopEnd = 158, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 8163,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 25, .vibratoDepth = 7, .vibratoWave = 0, .vibratoSweep = 168
};

extern cu8 _mailto_data[];
AudioSample _mailto = {
	.sampleStart = _mailto_data, .sampleLength = 3430, .loopEnd = 3430, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 4, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 0, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _Vanowarmailru_data[];
AudioSample _Vanowarmailru = {
	.sampleStart = _Vanowarmailru_data, .sampleLength = 559, .loopEnd = 559, .loopStart = 494, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 11025,
	.sampleType = 5, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 28, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _cEm0220002002_data[];
AudioSample _cEm0220002002 = {
	.sampleStart = _cEm0220002002_data, .sampleLength = 46, .loopEnd = 46, .loopStart = 14, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 6638,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 35, .vibratoDepth = 9, .vibratoWave = 4, .vibratoSweep = 172
};

extern cu8 _WolfsRainEnding1_data[];
AudioSample _WolfsRainEnding1 = {
	.sampleStart = _WolfsRainEnding1_data, .sampleLength = 0, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _Allleadsoundsby_data[];
AudioSample _Allleadsoundsby = {
	.sampleStart = _Allleadsoundsby_data, .sampleLength = 15808, .loopEnd = 15808, .loopStart = 11840, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 3522,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 16, .defaultPan = 160, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _WolfsRainEnding2_data[];
AudioSample _WolfsRainEnding2 = {
	.sampleStart = _WolfsRainEnding2_data, .sampleLength = 0, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _WolfsRainEnding3_data[];
AudioSample _WolfsRainEnding3 = {
	.sampleStart = _WolfsRainEnding3_data, .sampleLength = 0, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _WolfsRainEnding4_data[];
AudioSample _WolfsRainEnding4 = {
	.sampleStart = _WolfsRainEnding4_data, .sampleLength = 0, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _WolfsRainEnding5_data[];
AudioSample _WolfsRainEnding5 = {
	.sampleStart = _WolfsRainEnding5_data, .sampleLength = 0, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _WolfsRainEnding6_data[];
AudioSample _WolfsRainEnding6 = {
	.sampleStart = _WolfsRainEnding6_data, .sampleLength = 0, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _WolfsRainEnding7_data[];
AudioSample _WolfsRainEnding7 = {
	.sampleStart = _WolfsRainEnding7_data, .sampleLength = 0, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 48000,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _7_data[];
AudioSample _7 = {
	.sampleStart = _7_data, .sampleLength = 11904, .loopEnd = 11904, .loopStart = 512, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 11542,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 56, .defaultPan = 168, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _8_data[];
AudioSample _8 = {
	.sampleStart = _8_data, .sampleLength = 14192, .loopEnd = 14192, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 33437,
	.sampleType = 1, .globalVolume = 24, .defaultVolume = 32, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _YoshisIsland1_data[];
AudioSample _YoshisIsland1 = {
	.sampleStart = _YoshisIsland1_data, .sampleLength = 16213, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _somethingelse_data[];
AudioSample _somethingelse = {
	.sampleStart = _somethingelse_data, .sampleLength = 901, .loopEnd = 901, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _Thissongwasmadefrom_data[];
AudioSample _Thissongwasmadefrom = {
	.sampleStart = _Thissongwasmadefrom_data, .sampleLength = 23544, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _theclassicSuperNESgame_data[];
AudioSample _theclassicSuperNESgame = {
	.sampleStart = _theclassicSuperNESgame_data, .sampleLength = 12610, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _YoshisIslandsamples_data[];
AudioSample _YoshisIslandsamples = {
	.sampleStart = _YoshisIslandsamples_data, .sampleLength = 7032, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _aredirectlytakenfrom_data[];
AudioSample _aredirectlytakenfrom = {
	.sampleStart = _aredirectlytakenfrom_data, .sampleLength = 2009, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _thegameusingzSNES_data[];
AudioSample _thegameusingzSNES = {
	.sampleStart = _thegameusingzSNES_data, .sampleLength = 4794, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _patrickschneider2000_data[];
AudioSample _patrickschneider2000 = {
	.sampleStart = _patrickschneider2000_data, .sampleLength = 1582, .loopEnd = 0, .loopStart = 0, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 0, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _webde_data[];
AudioSample _webde = {
	.sampleStart = _webde_data, .sampleLength = 3675, .loopEnd = 3675, .loopStart = 1870, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

extern cu8 _greetzp2k_data[];
AudioSample _greetzp2k = {
	.sampleStart = _greetzp2k_data, .sampleLength = 10715, .loopEnd = 10715, .loopStart = 5156, .sustainLoopEnd = 0, .sustainLoopStart = 0, .middleCPitch = 44100,
	.sampleType = 1, .globalVolume = 64, .defaultVolume = 64, .defaultPan = 32, .vibratoSpeed = 0, .vibratoDepth = 0, .vibratoWave = 0, .vibratoSweep = 0
};

AudioSample *sampleList[] = {
	&_ChoirOohs, &_MaxVKick04, &_MaxVSNARE1, &_PianoHigh, &_kik, &_snare, &_Celesta2, &_GuitarNylon, &_ModernTalkingchiptune, &_ByEm022000, &_Hellotoallwho, &_knowsme, &_mailto, &_Vanowarmailru, &_cEm0220002002, &_WolfsRainEnding1, &_Allleadsoundsby, &_WolfsRainEnding2, &_WolfsRainEnding3, &_WolfsRainEnding4, &_WolfsRainEnding5, &_WolfsRainEnding6, &_WolfsRainEnding7, &_7, &_8, &_YoshisIsland1, &_somethingelse, &_Thissongwasmadefrom, &_theclassicSuperNESgame, &_YoshisIslandsamples, &_aredirectlytakenfrom, &_thegameusingzSNES, &_patrickschneider2000, &_webde, &_greetzp2k
};

cu16 numSamples = 35;

extern SongData _AreaA_DMA_OnlySong;
extern SongData _EM00220_Modern_TalkingSong;
extern SongData _GravityOfTheSituationSong;
extern SongData _yoshis_island_1Song;
SongData *songList[] = {
	&_AreaA_DMA_OnlySong, &_EM00220_Modern_TalkingSong, &_GravityOfTheSituationSong, &_yoshis_island_1Song
};

cu16 numSongs = 4;

